<?php

/**
 * @file
 * Implement hooks.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Alter a form.
 *
 * Implements hook_form_alter().
 *
 * @param mixed $form
 *   The form.
 * @param \Drupal\Core\Form\FormStateInterface $formState
 *   The form state.
 * @param int $formId
 *   The form id.
 */
function commerce_multisafepay_payments_form_alter(
  &$form,
  FormStateInterface $formState,
  $formId
) {

  if ($form['#step_id'] == 'order_information') {
    $name = null;
    /** @var \Drupal\commerce_payment\PaymentOption $payment_option */
    foreach ($form['payment_information']['#payment_options'] as $payment_option) {
      /** @var \Drupal\Core\Config\ImmutableConfig $config */
      $config = \Drupal::config('commerce_payment.commerce_payment_gateway.' . $payment_option->getId());
      if ('msp_applepay' == $config->get('plugin')) {
        $form['#attached']['library'][] = 'commerce_multisafepay_payments/applepay';
        $computed_settings['name'] = $payment_option->getId();
        $form['#attached']['drupalSettings']['commerce_multisafepay_payments']['applepay'] = $computed_settings;
        break;
      }
    }
  }
  // Check if the page is on review page.
  if (!empty($form['#step_id']) && $form['#step_id'] == 'review') {
    // Get Build info.
    $buildInfo = $formState->getBuildInfo();

    // Get Order.
    $order = $buildInfo['callback_object']->getOrder();

    // Get the Gateway.
    $paymentGateway = $order->payment_gateway->entity;

    // Check if the payment method is msp_ideal.
    if (isset($paymentGateway)
      && $paymentGateway->getPluginId() === 'msp_ideal'
    ) {
      $form['actions']['next']['#value'] = t(
        'Proceed to next step to choose your bank'
      );
    }
  }
}
