name: Code sniffer
on: pull_request
jobs:
  code_sniffer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Composer install
        run: composer install
      - name: Run code sniffer
        run: vendor/bin/phpcs --standard=vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml -n src/
